services:
  spring-app:
    build: .
    container_name: news-demo-spring
    image: news-demo-spring:dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/news
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: news-demo-spring-db
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    restart: always